### ISSUE TITLE
Select reserves grades using a priority scheme

### ISSUE THREAD

**Issue by JesperWe** [fossilfuelregistry/portal#8]
- [x] Prioritize grades in calculations
- [x] Show highest priority grade in pulldown

From highest to lowest priority:
2p
xp
1p
3p

And similar for c

**Comment by OpenOilUG** [comment]
UK shows all different classifications values at once in the drop down box so that it is not possible to know which of them has been chosen (the lines could only be one of the potential values)... https://dev.fossilfuelregistry.org/co2-forecast?country=gb&productionSourceId=1&projectionSourceId=5&reservesSourceId=5
